/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './route/__root'
import { Route as TasksRouteImport } from './route/tasks'
import { Route as SettingsRouteImport } from './route/settings'
import { Route as ConfigRouteImport } from './route/config'
import { Route as AboutRouteImport } from './route/about'
import { Route as IndexRouteImport } from './route/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
})
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
})
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
})
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfigRoute: ConfigRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
